# Selene Linter Configuration
# Diligent targets Lua 5.4 only
# Using basic configuration without std lib since lua54 not available in this Selene version

std = "lua53+awesome"

exclude = ["spec/*"]

[rules]
# Allow undefined awesome global (provided by AwesomeWM runtime)
#undefined_variable = "allow"
#incorrect_standard_library_use = "allow"
